### ISSUE TITLE
findOrCreate(id) doesn't create

### ISSUE THREAD

**Issue by CodeMonkeySteve** [PaulUithol/Backbone-relational#401]
I have an Organization model which has many Person models, where Person defines organization_id:

```
class @Organization extends Backbone.RelationalModel
  relations: [
    relatedModel: 'Person'
    type: Backbone.HasMany
    key: 'people'
    keyDestination: 'people_attributes'
    keySource: 'people'
    parse: true
    reverseRelation:
      key: 'organization'
      keySource: 'organization_id'
  ]
```

But if I instantiate a Person before the related Organization, the Organization model is never created.  E.g.:

```
new Person({organization_id: 42}).get('organization') == null
```

I've tracked this down to the fact that `findOrCreate` returns `null` when an id is passed but the model does not (yet) exist in the store.  I would expect it to create a sparse model (i.e. just an id), suitable for `fetch`ing.

I've tried modifying `findOrCreate` to add this behavior, but apparently lots of things expect the existing behavior (i.e. all the tests broke).
